os: linux
dist: bionic
language: shell
notifications:
  email: false
git:
  depth: 3
before_install:
  # Update Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update -y
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce qemu-user
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - export DOCKER_BUILD_KIT=1
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --driver docker-container --use
  - docker buildx inspect --bootstrap
install:
  - if [ "$TRAVIS_TAG" == "" ]; then
      docker buildx build --platform linux/arm/v7 -t DOCKER_USERNAME/flightfeeder .;
    else
      echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker buildx build --platform linux/arm/v7 -t $DOCKER_USERNAME/flightfeeder:$TRAVIS_TAG --push .;
    fi