os: linux
dist: bionic
language: minimal
notifications:
  email: false
git:
  depth: 3
before_install:
  # Update Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Create new docker builder
  - docker buildx use pibuilder
  - docker buildx inspect --bootstrap
  - docker buildx ls
install:
  # Build docker image
  - docker buildx --platform linux/arm/v7 -t $DOCKER_USERNAME/flightfeeder:${TRAVIS_TAG} .
before_deploy:
  # List local docker images
  - docker images
  # Login to docker
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/flightfeeder:${TRAVIS_TAG}
  on:
    tags: true
    all_branches: false