version: "3.7"
services:
  fr24feed-piaware:
    image: "thomasreiser/fr24feed-piaware"
    restart: unless-stopped
    environment: 
      - "FR24FEED_FR24KEY=MY_SHARING_KEY"
      - "PIAWARE_FEEDER_DASH_ID=MY_FEEDER_ID"
      - "HTML_SITE_LAT=MY_SITE_LAT"
      - "HTML_SITE_LON=MY_SITE_LON"
      - "HTML_SITE_NAME=MY_SITE_NAME"
      - "PANORAMA_ID=MY_PANORAMA_ID"
    devices:
      - "/dev/bus/usb"
    # ports
    # 8754 - DUMP1090 server port
    # 8080 - HTTP server port
    ports:
      - "8754:8754"
      - "8080:8080"
    logging:
      options:
        max-size: "30m"
